name: Clean Failed/Cancelled Workflow Runs

on:
  workflow_dispatch:

jobs:
  clean-failed-cancelled:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all failed and cancelled workflow runs
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          REPO: ${{ github.repository }}
          WORKFLOW_NAME: ${{ github.workflow }}
        run: |
          echo "Fetching failed and cancelled workflow runs for $REPO"
          page=1
          while :; do
            response=$(curl -s -H "Authorization: token $GH_PAT" \
              "https://api.github.com/repos/$REPO/actions/runs?per_page=100&page=$page")
            run_count=$(echo "$response" | jq '.workflow_runs | length')
            if [ "$run_count" -eq 0 ]; then
              break
            fi
            runs=$(echo "$response" | jq '.workflow_runs[] | select(.conclusion=="failure" or .conclusion=="cancelled") | .id')
            for run_id in $runs; do
              echo "Deleting run $run_id"
              curl -s -X DELETE -H "Authorization: token $GH_PAT" \
                "https://api.github.com/repos/$REPO/actions/runs/$run_id"
            done
            page=$((page+1))
          done

          # 额外：删除本 workflow 的所有 run（包括成功的）
          echo "Deleting all runs of this workflow itself (including successful runs)..."
          workflow_id=$(curl -s -H "Authorization: token $GH_PAT" \
            "https://api.github.com/repos/$REPO/actions/workflows" | jq ".workflows[] | select(.name == \"$WORKFLOW_NAME\") | .id")

          if [ -n "$workflow_id" ]; then
            page=1
            while :; do
              response=$(curl -s -H "Authorization: token $GH_PAT" \
                "https://api.github.com/repos/$REPO/actions/workflows/$workflow_id/runs?per_page=100&page=$page")
              run_count=$(echo "$response" | jq '.workflow_runs | length')
              if [ "$run_count" -eq 0 ]; then
                break
              fi
              runs=$(echo "$response" | jq '.workflow_runs[] | .id')
              for run_id in $runs; do
                echo "Deleting self run $run_id"
                curl -s -X DELETE -H "Authorization: token $GH_PAT" \
                  "https://api.github.com/repos/$REPO/actions/runs/$run_id"
              done
              page=$((page+1))
            done
          fi
          echo "All done." 